# Generated by Django 5.2.8 on 2025-12-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('civil', 'Civil'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('carpenter', 'Carpenter'), ('misc', 'Miscellaneous'), ('tiles', 'Tiles')], max_length=20)),
                ('labour_count', models.IntegerField(default=0)),
                ('material_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='civil_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='CivilTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('labour_count', models.IntegerField(default=0)),
                ('material_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_teams', to='civil_app.site')),
            ],
            options={
                'unique_together': {('site', 'team_number')},
            },
        ),
    ]
