# Generated by Django 5.2.8 on 2025-12-09 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='civilteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='civilteam',
            name='team_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='civilteam',
            name='team_number',
        ),
    ]
