# Generated by Django 5.2.8 on 2025-12-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0002_alter_civilteam_unique_together_civilteam_team_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilteam',
            old_name='labour_count',
            new_name='helper_count',
        ),
        migrations.RenameField(
            model_name='civilteam',
            old_name='material_count',
            new_name='mason_count',
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='location',
        ),
        migrations.AddField(
            model_name='civilteam',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CivilSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mason_count', models.IntegerField(default=0)),
                ('helper_count', models.IntegerField(default=0)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_details', to='civil_app.site')),
            ],
        ),
    ]
