# Generated by Django 5.2.8 on 2025-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0003_rename_labour_count_civilteam_helper_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilteam',
            old_name='payment',
            new_name='helper_payment',
        ),
        migrations.RemoveField(
            model_name='civilteam',
            name='helper_count',
        ),
        migrations.RemoveField(
            model_name='civilteam',
            name='mason_count',
        ),
        migrations.AddField(
            model_name='civilteam',
            name='mason_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
