# Generated by Django 5.2.8 on 2025-12-10 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0005_dailyentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='dailyentry',
            old_name='labour_count',
            new_name='labour',
        ),
        migrations.RenameField(
            model_name='dailyentry',
            old_name='material_count',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='civilsectiondetail',
            name='helper_count',
        ),
        migrations.RemoveField(
            model_name='civilsectiondetail',
            name='mason_count',
        ),
        migrations.RemoveField(
            model_name='civilsectiondetail',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='section',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='team',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='helper_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='mason_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='section_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='section_name',
            field=models.CharField(max_length=100),
        ),
    ]
