# Generated by Django 5.2.8 on 2025-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0006_rename_date_dailyentry_entry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='labour',
            new_name='labour_count',
        ),
        migrations.RenameField(
            model_name='dailyentry',
            old_name='material',
            new_name='material_count',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='helper_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='mason_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
