# Generated by Django 5.2.8 on 2025-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0007_rename_labour_dailyentry_labour_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilteam',
            name='helper_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilteam',
            name='helper_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='civilteam',
            name='mason_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilteam',
            name='mason_rate',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='material_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
