# Generated by Django 5.2.8 on 2025-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0008_civilteam_helper_count_civilteam_helper_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='labour_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='material_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
