# Generated by Django 5.2.8 on 2025-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0010_alter_civilteam_helper_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilteam',
            name='helper_rate',
        ),
        migrations.RemoveField(
            model_name='civilteam',
            name='mason_rate',
        ),
        migrations.AlterField(
            model_name='civilteam',
            name='helper_payment',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='civilteam',
            name='mason_payment',
            field=models.DecimalField(decimal_places=2, default=1350, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
