# Generated by Django 5.2.8 on 2025-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0011_remove_civilteam_helper_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilteam',
            name='helper_rate',
            field=models.DecimalField(decimal_places=2, default=950, max_digits=10),
        ),
        migrations.AddField(
            model_name='civilteam',
            name='mason_rate',
            field=models.DecimalField(decimal_places=2, default=1350, max_digits=10),
        ),
    ]
