# Generated by Django 5.2.8 on 2025-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0012_civilteam_helper_rate_civilteam_mason_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilteam',
            name='helper_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='civilteam',
            name='helper_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='civilteam',
            name='mason_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='civilteam',
            name='mason_rate',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
