# Generated by Django 5.2.8 on 2025-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0013_alter_civilteam_helper_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
